language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - py.test --cov-config .coveragerc --cov=grinpy tests/
  - coveralls
