language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - coverage run --source=grinpy setup.py
  - coveralls
